name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: All things angular
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.2
      with:
        github_access_token: ${{ secrets.ACCESS_TOKEN }}
        base_href: https://diegodoniss.github.io/e-comerce/
        deploy_branch: gh-pages
        angular_dist_build_folder: dist
